# Generated by Django 5.2.3 on 2026-03-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrookeryrole',
            name='role',
            field=models.ForeignKey(help_text='Defines the role of the user within a company context', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role'),
        ),
    ]
