# Generated by Django 5.2.3 on 2026-03-25 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_userrookeryrole_role'),
        ('users', '0002_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrookeryrole',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'role'), name='unique_user_company_role'),
        ),
    ]
