# Generated by Django 5.2.3 on 2026-03-25 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_userrookeryrole_unique_user_company_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userservice',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_user_service'),
        ),
    ]
