# Generated by Django 5.2.3 on 2026-03-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='owner', max_length=20),
            preserve_default=False,
        ),
    ]
