# Generated by Django 5.2.3 on 2026-04-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertyowner_user_delete_propertytenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='title',
            field=models.CharField(blank=True, choices=[('', '---'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Ing.', 'Ing.')], default='', help_text='Title of the owner', max_length=10),
        ),
    ]
