# Generated by Django 5.2.3 on 2026-04-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_serviceperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_charges', to='properties.company')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_charges', to='properties.property')),
                ('service_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='properties.serviceperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('service_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.servicecharge')),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicecharge',
            constraint=models.UniqueConstraint(fields=('property', 'service_period'), name='unique_property_service_period_charge'),
        ),
    ]
