# Generated by Django 5.2.3 on 2026-04-28 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_servicecharge_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='notice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceperiod',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
