# Generated by Django 5.2.3 on 2026-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_payment_created_at_servicecharge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='display_label',
            field=models.CharField(blank=True, help_text='UI label (default: first_name + property name)', max_length=255),
        ),
    ]
