# Generated by Django 5.2.3 on 2026-03-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
